
import React from 'react';
import { AlertTriangleIcon } from './icons/AlertTriangleIcon';

const Disclaimer: React.FC = () => {
  return (
    <div className="mt-12 text-center text-xs text-slate-500 bg-slate-800/30 p-4 rounded-lg border border-slate-700 flex items-center justify-center gap-3">
        <AlertTriangleIcon className="w-8 h-8 text-yellow-500 flex-shrink-0" />
        <p>
            <strong>Disclaimer:</strong> The analysis provided by TradeStrateg AI is for informational and educational purposes only. It is generated by an AI model and should not be considered as financial advice. Always conduct your own research and consult with a qualified financial advisor before making any investment decisions.
        </p>
    </div>
  );
};

export default Disclaimer;
